<BugTester>:
    Button:
        
        disabled: True
        #Image wasn't scaling to fit the window grrrr


<GamePiece>:
    id: gamepiece
    size_hint:(None, None)
    group: self.player_color
    border: (0,0,0,0)
    


    AnchorLayout:
        id: layout
        center: root.center
        on_size: self.size = root.size
        anchor_x: "left"
        anchor_y: "bottom"

        canvas:
            Color:
                rgba: 1,0,1,1
            Ellipse:
                id: circle
                size: (root.width/2.5, root.height/3)
                #pos: -15, -20
                pos: root.pos

        Label:
            id: number
            text: str(root.number)
            color: (1,1,1,1)
            font_size: root.height/4
            bold: True
            #pos: root.pos